Automatic testing and building
Neovici/cosmoz-frontend-rtd pull request #13
Opened 2018-03-09 14:25 UTC by dotpointer

Details about automatic testing and building, transcribed Youtube video information and added some extra details.

2018-03-15 13:17 UTC, JockeCK requested changes

2018-03-15 13:17 UTC, JockeCK commented on docs/public/50-build-test.rst
> +    and install it.
Some more details about which choices to make during install would be nice. UTf8 yes no, MSYS2, MINGW, etc.

2018-03-16 10:03 UTC, Wurper approved these changes

2018-03-19 14:44 UTC, dotpointer commented on docs/public/50-build-test.rst
> +    and install it.
Added more details about Ruby and Travis-CI installation in Windows, please have a look.

2018-03-26 11:48 UTC, JockeCK approved these changes

2018-03-26 11:50 UTC, merged